In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
file = "./Impact_of_Remote_Work_on_Mental_Health.csv"

In [3]:
mentalHealthDf = pd.read_csv(file)
mentalHealthDf.head()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,Medium,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,Medium,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,Medium,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,High,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,High,NaN,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America

In [4]:
mentalHealthDf.columns

Index(['Employee_ID', 'Age', 'Gender', 'Job_Role', 'Industry',
       'Years_of_Experience', 'Work_Location', 'Hours_Worked_Per_Week',
       'Number_of_Virtual_Meetings', 'Work_Life_Balance_Rating',
       'Stress_Level', 'Mental_Health_Condition',
       'Access_to_Mental_Health_Resources', 'Productivity_Change',
       'Social_Isolation_Rating', 'Satisfaction_with_Remote_Work',
       'Company_Support_for_Remote_Work', 'Physical_Activity', 'Sleep_Quality',
       'Region'],
      dtype='object')

In [5]:
mentalHealthDf['Mental_Health_Condition'] = mentalHealthDf['Mental_Health_Condition'].fillna('Healthy')

mentalHealthDf

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,Medium,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,Medium,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,Medium,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,High,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,High,Healthy,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,EMP4996,32,Male,Sales,Consulting,4,Onsite,24,2,5,High,Burnout,Yes,Decrease,4,Neutral,1,Weekly,Average,Asia
4996,EMP4997,39,Female,Sales,Healthcare,27,Onsite,48,15,1,Low,Depression,Yes,Decrease,1,Satisfied,1,NaN,Average,Africa
4997,EMP4998,42,Female,Sales,Healthcare,21,Hybrid,34,1,4,High,Burnout,No,Increase,3,Satisfied,1,Daily,Poor,Oceania
4998,EMP4999,27,Female,Sales,Healthcare,26,Remote,58,0,5,Low,Healthy,Yes,Increase,3,Unsatisfied,4,Daily,Average,Asia
4999,EMP5000,29,Male,HR,IT,30,Onsite,20,15,1,Low,Depression,Yes,No Change,3,Unsatisfied,5,NaN,Poor,Asia

In [6]:
mentalHealthDfReduced = mentalHealthDf[['Sleep_Quality', 'Stress_Level', 'Mental_Health_Condition']]

In [7]:
mentalHealthDfHealth = pd.get_dummies(mentalHealthDf['Mental_Health_Condition'])

In [8]:
mentalHealthStressSleepandCond = pd.concat([mentalHealthDfReduced, mentalHealthDfHealth], axis = 1)

mentalHealthStressSleepandCond

,Sleep_Quality,Stress_Level,Mental_Health_Condition,Anxiety,Burnout,Depression,Healthy
0,Good,Medium,Depression,False,False,True,False
1,Good,Medium,Anxiety,True,False,False,False
2,Poor,Medium,Anxiety,True,False,False,False
3,Poor,High,Depression,False,False,True,False
4,Average,High,Healthy,False,False,False,True
...,...,...,...,...,...,...,...
4995,Average,High,Burnout,False,True,False,False
4996,Average,Low,Depression,False,False,True,False
4997,Poor,High,Burnout,False,True,False,False
4998,Average,Low,Healthy,False,False,False,True
4999,Poor,Low,Depression,False,False,True,False

In [9]:
sleepDf = mentalHealthStressSleepandCond.groupby(['Stress_Level', 'Sleep_Quality']).sum(numeric_only=True).reset_index()

sleepDfbyCond = sleepDf[['Stress_Level', 'Sleep_Quality', 'Anxiety', 'Burnout', 'Depression', 'Healthy']]

sleepDfbyCond['Total'] = sleepDfbyCond[['Anxiety', 'Burnout', 'Depression', 'Healthy']].sum(axis=1)

sleepDfbyCond

  Stress_Level Sleep_Quality  Anxiety  Burnout  Depression  Healthy  Total
0         High       Average      147      147         132      135    561
1         High          Good      139      136         125      141    541
2         High          Poor      152      162         144      126    584
3          Low       Average      147      134         136      119    536
4          Low          Good      146      142         136      140    564
5          Low          Poor      135      137         144      129    545
6       Medium       Average      154      123         140      114    531
7       Medium          Good      135      153         153      141    582
8       Medium          Poor      123      146         136      151    556